### PR TITLE
AudioService: don't allow changing zen modes on devices with a Alert …

### PR DESCRIPTION
**Pull request by Thecrazyskull**
…Slider

### CODE REVIEW

**Comment by Thecrazyskull** [comment]
@leonfish77101

**Comment by Thecrazyskull** [comment]
@JayFan1201

**Comment by leonfish77101** [comment]
@JayFan1201 Please take a look at it, thanks

**Comment by axlecho** [comment]
@Thecrazyskull  hi,Thecrazyskull does this commits purpose to sync the zenmode state with the three-state key?
but some devices has no three-state key(like OPO)
and if you really want to do that ,you need to block a lot of interface provided in android sdk because there are many operations can change the zenmode. (setRingMode etc.)

**Comment by Thecrazyskull** [comment]
@axlecho this branch is only used for the oneplus3, so i didn't bother guarding this code to prevent it from running on devices without alert slider.
Also, this code only prevents volume keys from changing zen modes because alert slider should still be able to change zen modes.

**Comment by axlecho** [comment]
@Thecrazyskull consider to do this in rom

**Comment by Thecrazyskull** [comment]
@axlecho what do you mean?

**Pull request closed without merging**
